apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: svc-deploy
spec:
  params:
    - name: contextDir
      description: the context directory from where to build the application
    - name: destinationImage
      description: the fully qualified image name
  workspaces:
    - name: workspace
  tasks:
    - name: build-java-app
      taskRef:
        name: build-app
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: contextDir
          value: $(params.contextDir)
        - name: destinationImage
          value: $(params.destinationImage)
    - name: deploy-kubernetes-service
      taskRef:
        name: openshift-client
      runAfter:
        - build-java-app
      params:
        - name: SCRIPT
          value: |
            kubectl create deployment greeter --port=8080 --image=$(params.destinationImage)
            kubectl expose deployment/greeter --port=8080 --target-port=8080 --type=NodePort